services:
  app:
    container_name: test_app
    command: [ "go", "test", "-v", "./..." ]
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=test_user
      - DB_PASSWORD=Test@1234
      - DB_NAME=testdatabase
      - PGSSLMODE=disable
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app-network

  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=test_user
      - POSTGRES_PASSWORD=Test@1234
      - POSTGRES_DB=testdatabase
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - app-network

networks:
  app-network:
    driver: bridge