services:
  test_app:
    container_name: test_app
    command: [ "go", "test", "-v", "-tags=unit", "./..." ]
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8080"
    environment:
      - DB_HOST=db_test
      - DB_PORT=5432
      - DB_USER=test_user
      - DB_PASSWORD=Test@1234
      - DB_NAME=testdatabase
      - PGSSLMODE=disable
    depends_on:
      db_test:
        condition: service_healthy
    networks:
      - test-network

  db_test:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=test_user
      - POSTGRES_PASSWORD=Test@1234
      - POSTGRES_DB=testdatabase
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U test_user"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - test-network

networks:
  test-network:
    driver: bridge